spring:
    datasource:
        # driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: org.h2.Driver
        # url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        url: jdbc:h2:mem:wx_data
        username: ${MYSQL_USERNAME:sa}
        password: ${MYSQL_PASSWORD:123456}
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql
    h2:
        console:
            enabled: true
            path: /h2-console

springfox:
    documentation:
        swagger-ui:
            enabled: true