spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    redis:
        host: 43.130.230.251
        port: 6379
        password: 123456

springfox:
    documentation:
        swagger-ui:
            enabled: false
